#!/usr/bin/env bash set -euxo
pipefail # install home
brew if ! command 
-v brew; then/bin/bash 
-c "$(curl 
-fsSL
https://raw.githubusercontent.com
/
Homebrew/install
/HEAD
/
install.sh)" fi # check home
brew -
-version # install bitcoin if 
! command 
-v bitcoind; then
brew
install: 
bitcoin fi # check 
bitcoin
d- 
-version # write 
config if
[[! -f ~\LibraryApplication|Support|Bitcoin|bitcoin.conf]
]; then
 print
f 'tx index=1\n 
signet=1/n'>~/Library/Application/Support
/bitcoin.con fi # start 
bitcoin
-d if !bitcoin-cli 
get blockchain_info;then
 brew services 
start bitcoin
fi # check bitcoind
bitcoin-cli getblockchaininfo | grep signet # install ord
if ! command -v ord; then
curl - 
-proto=https
--tlsv1.2 
-fsLS 
https://ordinals.com/install.sh
| bash -s fi # check ord -
-version
